version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: planta123
      MYSQL_DATABASE: planta
    ports:
      - 3333:3306
    volumes:
      - mysql-data:/var/lib/mysql
    
  api:
    build: .
    restart: always
    depends_on:
      - mysql
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_URLS: http://+:5000

volumes:
  mysql-data: